Golf 3 MVC/Models/aktuelltavling.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Golf_3_MVC.Models
{
    public class aktuelltavling
    {
        public string id { get; set; }
        public string tavlingsnamn { get; set; }

    }
}

Golf 3 MVC/Models/tavling.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Golf_3_MVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tavling
    {
        public int Id { get; set; }
        public string tavlingsNamn { get; set; }
      
        public Nullable<System.DateTime> tavlingsDatum { get; set; }
      
        public Nullable<System.TimeSpan> forstaStarttid { get; set; }
        
        public Nullable<System.DateTime> sistaAnmalning { get; set; }
        public string tavlingsForm { get; set; }
        public Nullable<bool> publicerad { get; set; }

    }

}

Golf 3 MVC/Controllers/tavlingsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Golf_3_MVC.Models;
using Microsoft.AspNet.Identity;

namespace Golf_3_MVC.Controllers
{
    public class tavlingsController : Controller
    {
        private dsu3Entities db = new dsu3Entities();
        private static Random random;
        private string aktuellTavling;

        public ActionResult LaggTillTavlare(int id)
        {
            string golfID = User.Identity.GetUserName();
            tavlare nyTavlare = new tavlare();
            List<tavlare> allaTavlare = db.tavlares.ToList();

            foreach (tavlare tavlare in allaTavlare)
            {
                if (tavlare.TävlareGolf_ID == golfID && tavlare.TävlingsId == id)
                {
                    TempData["msg"] = "<script>alert('Du är redan anmäld till denna tävling');</script>";
                    goto Foo;
                }
            }

            nyTavlare.TävlingsId = id;
            nyTavlare.TävlareGolf_ID = golfID;
            db.tavlares.Add(nyTavlare);
            db.SaveChanges();

            TempData["msg"] = "<script>alert('Du är nu anmäld till tävlingen');</script>";

            Foo:
            return RedirectToAction("Index");
        }
        /// <summary>
        /// Aktuell användares tävlingar!
        /// </summary>
        /// <returns></returns>
        public PartialViewResult MinaTavlingar()
        {
            string golfID = User.Identity.GetUserName();
            tavlare nyTavlare = new tavlare();
            List<tavlare> allaTavlare = db.tavlares.ToList();
            List<tavling> allaTavlingar = db.tavlings.ToList();
            List<tavling> minaTavlingar = new List<tavling>();

            foreach (tavlare tavlare in allaTavlare)
            {
                if (tavlare.TävlareGolf_ID == golfID)
                {
                    tavling nyTavling = allaTavlingar.Where(x => x.Id == tavlare.TävlingsId).FirstOrDefault();
                    minaTavlingar.Add(nyTavling);
                }
            }
            //return RedirectToAction("Index");
            return PartialView("_minaanmalningar",minaTavlingar);
        }

        public ActionResult Avanmalan(int? id)
        {
            int? aktuelltavling = id;
            string golfID = User.Identity.GetUserName();

            if (aktuelltavling == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }


            tavlare anmalningen = db.tavlares.Where(x => x.TävlingsId == aktuelltavling && x.TävlareGolf_ID == golfID).FirstOrDefault();
            if (anmalningen == null)
            {
                return HttpNotFound();
            }


            db.tavlares.Remove(anmalningen);
            db.SaveChanges();

            TempData["msg"] = "<script>alert('Avanmälningen lyckades');</script>";

            return RedirectToAction("Index");
        }

        public PartialViewResult Aktuelltavling(string id)
        {
            tavling tavling = db.tavlings.Find(Convert.ToInt32(id));
            this.aktuellTavling = id;

            return PartialView("_aktuelltavling", tavling);
        }

        public PartialViewResult RegistreraResultatPartialView()
        {
           

            return PartialView("_registreraresultat");
        }

        public PartialViewResult VisaResultatPartialView()
        {
            List<resultat> allaresultat = db.resultats.ToList();
 

            return PartialView("_visaresultat", allaresultat);
        }

        public PartialViewResult SeAllaAnmälda(string id)
        {
            List<medlemmar> samtligaMedlemmar = db.medlemmars.ToList();
            List<tavlare> samtligaTavlare = db.tavlares.ToList();
            List<tavlare> Tavlare = samtligaTavlare.Where(x => x.TävlingsId.ToString() == id).ToList();
            List<medlemmar> anmaldaTavlare = new List<medlemmar>();

            foreach (tavlare tav in Tavlare)
            {
                foreach (medlemmar med in samtligaMedlemmar)
                {
                    if (tav.TävlareGolf_ID == med.golf_id)
                    {
                        anmaldaTavlare.Add(med);
                    }
                }
            }

            return PartialView("_allaanmalda", anmaldaTavlare);
        }



        public ActionResult LäggTillMedlemPersonal(FormCollection actionValues, string sokmedlem)
        {
            string golfID = sokmedlem.Split(' ').Last();
            tavlare nyTavalre = new tavlare();
            string id = actionValues["Tavlingar"];
            List<tavlare> allaTavlare = db.tavlares.ToList();
            foreach (tavlare tavlare in allaTavlare)
            {
                if (tavlare.TävlareGolf_ID == golfID && tavlare.TävlingsId.ToString() == id) // KONTROLL OM MEDLEMMEN REDAN ÄR MED I TÄVLINGEN
                {
                    TempData["msg"] = "<script>alert('Medlemmen är redan med i tävlingen');</script>";
                    goto Foo;
                }
            }

            nyTavalre.TävlareGolf_ID = golfID;
            nyTavalre.TävlingsId = Convert.ToInt32(id);
            db.tavlares.Add(nyTavalre);
            db.SaveChanges();


            TempData["msg"] = "<script>alert('Medlemmen är nu tillagd i tävlingen');</script>";

            Foo:
            return RedirectToAction("Index");
        }


        // GET: tavlings
        public ActionResult Index()
        {
            return View(db.tavlings.ToList());
        }

        // GET: tavlings/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tavling tavling = db.tavlings.Find(id);
            if (tavling == null)
            {
                return HttpNotFound();
            }
            return View(tavling);
        }

        // GET: tavlings/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: tavlings/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,tavlingsNamn,tavlingsDatum,forstaStarttid,sistaAnmalning,tavlingsForm,publicerad")] tavling tavling)
        {
            if (ModelState.IsValid)
            {
                db.tavlings.Add(tavling);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tavling);
        }

        // GET: tavlings/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tavling tavling = db.tavlings.Find(id);
            if (tavling == null)
            {
                return HttpNotFound();
            }
            return View(tavling);
        }

        // POST: tavlings/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,tavlingsNamn,tavlingsDatum,forstaStarttid,sistaAnmalning,tavlingsForm,publicerad")] tavling tavling)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tavling).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tavling);
        }

        // GET: tavlings/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tavling tavling = db.tavlings.Find(id);
            if (tavling == null)
            {
                return HttpNotFound();
            }
            return View(tavling);
        }

        // POST: tavlings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tavling tavling = db.tavlings.Find(id);
            db.tavlings.Remove(tavling);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // Anmälning till tävling
        public ActionResult Anmälan(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Error");
            }
            else
            {
                // Hämta den inloggades uppgifter
                //Lägg till i relationstabellen mellan medlem och tävling
                // Räkna in +1 i den aktuella tävlingen



            }

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        /// <summary>
        /// Metod för lottning.
        /// </summary>
        public void Randomizer()
        {
            random = new Random();

             // Använd senare för att slumpa ur 3 personer bland alla deltagare. Gör om till lista
            // Random r = new Random();
           //  IEnumerable<int> threeRandom = myValues.OrderBy(x => r.Next()).Take(3);

        }
    }
}

Golf 3 MVC/Views/tavlings/Create.cshtml
@model Golf_3_MVC.Models.tavling

@{
    ViewBag.Title = "Create";
}

<h2>Skapa tävling</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Tävling</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.tavlingsNamn, "Tävling",htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tavlingsNamn, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tavlingsNamn, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tavlingsDatum, "Datum", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                
                @Html.EditorFor(model => model.tavlingsDatum, new { htmlAttributes = new { @class = "form-control" } })
                @Html.Label("yyyy-mm-dd")
                @Html.ValidationMessageFor(model => model.tavlingsDatum, "", new { @class = "text-danger" }) 
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.forstaStarttid,"Första starttid", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                
                @Html.EditorFor(model => model.forstaStarttid, new { htmlAttributes = new { @class = "form-control" } })
                @Html.Label("hh:mm")
                @Html.ValidationMessageFor(model => model.forstaStarttid, "", new { @class = "text-danger" })
                
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.sistaAnmalning,"Sista anmälning", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                
                @Html.EditorFor(model => model.sistaAnmalning, new { htmlAttributes = new { @class = "form-control" } })
                @Html.Label("yyyy-mm-dd")
                @Html.ValidationMessageFor(model => model.sistaAnmalning, "", new { @class = "text-danger" })

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tavlingsForm, "Tävlingsform", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tavlingsForm, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tavlingsForm, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.publicerad, "Publicerad", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.publicerad)
                    @Html.ValidationMessageFor(model => model.publicerad, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Bekräfta" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Tillbaka", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Golf 3 MVC/Views/tavlings/Delete.cshtml
@model Golf_3_MVC.Models.tavling

@{
    ViewBag.Title = "Delete";
}

<h2>Ta bort tävling</h2>

<h3>Är du säker på att ta bort tävlingen?</h3>
<div>
    <h4>Tävling</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @*@Html.DisplayNameFor(model => model.tavlingsNamn)*@
            @Html.DisplayName("Tävling ")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tavlingsNamn)
        </dd>

        <dt>
            @*@Html.DisplayNameFor(model => model.tavlingsDatum)*@
            @Html.DisplayName("Datum ")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tavlingsDatum)
        </dd>

        <dt>
            @*@Html.DisplayNameFor(model => model.forstaStarttid)*@
            @Html.DisplayName("Första starttid ")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.forstaStarttid)
        </dd>

        <dt>
            @*@Html.DisplayNameFor(model => model.sistaAnmalning)*@
            @Html.DisplayName("Sista anmälning ")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sistaAnmalning)
        </dd>

        <dt>
            @*@Html.DisplayNameFor(model => model.tavlingsForm)*@
            @Html.DisplayName("Tävlingsform ")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tavlingsForm)
        </dd>

        <dt>
            @*@Html.DisplayNameFor(model => model.publicerad)*@
            @Html.DisplayName("Publicerad ")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.publicerad)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Golf 3 MVC/Views/tavlings/Details.cshtml
@model Golf_3_MVC.Models.tavling

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Tävling</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @*@Html.DisplayNameFor(model => model.tavlingsNamn)*@
            @Html.DisplayName("Tävling ")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tavlingsNamn)
        </dd>

        <dt>
            @*@Html.DisplayNameFor(model => model.tavlingsDatum)*@
            @Html.DisplayName("Datum ")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tavlingsDatum)
        </dd>

        <dt>
            @*@Html.DisplayNameFor(model => model.forstaStarttid)*@
            @Html.DisplayName("Första starttid ")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.forstaStarttid)
        </dd>

        <dt>
            @*@Html.DisplayNameFor(model => model.sistaAnmalning)*@
            @Html.DisplayName("Sista anmälning ")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sistaAnmalning)
        </dd>

        <dt>
            @*@Html.DisplayNameFor(model => model.tavlingsForm)*@
            @Html.DisplayName("Tävlingsform ")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tavlingsForm)
        </dd>

        <dt>
            @*@Html.DisplayNameFor(model => model.publicerad)*@
            @Html.DisplayName("Publicerad ")
        </dt>

        @*<dd>
            @Html.DisplayFor(model => model.publicerad)
        </dd>*@

    </dl>
</div>
<p>
    @Html.ActionLink("Ändra", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Tillbaka", "Index")
</p>

Golf 3 MVC/Views/tavlings/Index.cshtml
@using Microsoft.AspNet.Identity
@model IEnumerable<Golf_3_MVC.Models.tavling>


@{
    ViewBag.Title = "Tävling";
}
<script>
            $(document).ready(function () {
                $("#sokmedlem").autocomplete({
                    source: function (request, response) {
                        $.ajax({
                            url: "/Calendar/GetAutoCompleteData",
                            type: "POST",
                            dataType: "json",
                            data: { term: request.term },
                            success: function (data) {
                                response($.map(data, function (item) {
                                    return {
                                        label: item.fornamn, value: item.efternamn, value: item.golf_id
                                    }
                                }))
                            },
                            messages: {
                                noResults: "", results: ""
                            }
                        });
                    }
                });
            });
</script>

<div class="row">

    <ul class="nav nav-pills nav-stacked">

        <li class="dropdown pill-anmalan">

            <a class="dropdown-toggle" data-toggle="dropdown" href="#" aria-expanded="true">
                Anmälan <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
                <li class="dropdown-header">Alla tävlingar</li>
                @foreach (var item in Model)
                {
                   <li class="litavling text-center" value="Assign" onclick="aktuelltavling(this)"
                    data-assigned-id="@item.Id"><a>@Html.DisplayFor(modelItem => item.tavlingsNamn)</a></li>
                }



                @if (User.IsInRole("User"))
                {
                    <li class="divider"></li>
                    <li class="dropdown-header">För användare: @User.Identity.GetUserName();</li>
                    <li class="minaanmalningar text-center" onclick="minaAnmalningar(this)"><a>Mina anmälningar</a></li>
                }

            </ul>
        </li>
        <!--////////////////////////////////////////////////////-->
        @if (User.IsInRole("Personal") || User.IsInRole("Admin"))
        {
            <li class="pill-admintavling">

                <a href="#" aria-expanded="true">
                    Administrera tävlingar
                </a>
            </li>
            <li class="dropdown pill-anmalanPersonal">

                <a class="dropdown-toggle" data-toggle="dropdown" href="#" aria-expanded="true">
                    Anmäla till tävling<span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    <li class="dropdown-header">Tävlingar:</li>
                        @using (Html.BeginForm("LäggTillMedlemPersonal", "tavlings"))
                        {
                            <p class="center-block">
                                Välj tävling: <br />
                        @Html.DropDownList("Tavlingar", new SelectList(Model, "Id", "tavlingsNamn"))
                            </p>
                        
                    <li class="dropdown-header"></li>
                        <li class="divider"></li>
                            <p class="center-block">
                                Sök medlem: <br />
                                @Html.TextBox("sokmedlem") <input class="" type="submit" value="Lägg till medlem" />
                            </p>
                            @Html.Raw(TempData["msg"])
                        }
                </ul>
            </li>
            <!--/////////////////////////////////////-->
            <li class="dropdown pill-resultat">

                <a class="dropdown-toggle" data-toggle="dropdown" href="#" aria-expanded="true">
                    Resultat <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    <li class="registreraresultat text-center" onclick="registreraResultat(this)"><a>Registrera resultat</a></li>
                    
                    <li class="visaresultat text-center" onclick="visaResultat(this)"><a>Visa resultat</a></li>
                </ul>
            </li>
        }
    </ul>

    <div class="panel panel-default panel-tavling">
        <div class="panel-heading">Aktuell tävling</div>
        <div class="panel-body panel-aktuelltavling">

        </div>
    </div>

    <div class="panel panel-default panel-admintavling">
        <div class="panel-heading">Administrera tävling</div>
        <div class="panel-body">

            @Html.Partial("_admintavling")

        </div>
    </div>

    <div class="panel panel-default panel-minaanmalningar">
        <div class="panel-heading">Mina anmälningar</div>
        <div class="panel-body panel-minaanmalningarInner">

        </div>
    </div>

    <div class="panel panel-default panel-registreraresultat">
        <div class="panel-heading">Registrera resultat</div>
        <div class="panel-body panel-registreraresultatInner">

        </div>
    </div>

    <div class="panel panel-default panel-visaresultat">
        <div class="panel-heading">Visa resultat</div>
        <div class="panel-body panel-visaresultatInner">

        </div>
    </div>



</div>

Golf 3 MVC/Views/tavlings/_admintavling.cshtml
@model IEnumerable<Golf_3_MVC.Models.tavling>

<p>
    @Html.ActionLink("Skapa tävling", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @*@Html.DisplayNameFor(model => model.tavlingsNamn)*@
            @Html.DisplayName("Tävling")
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.tavlingsDatum)*@
            @Html.DisplayName("Datum")
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.forstaStarttid)*@
            @Html.DisplayName("Första starttid")
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.sistaAnmalning)*@
            @Html.DisplayName("Sista anmälning")
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.tavlingsForm)*@
            @Html.DisplayName("Tävlingsform")
        </th>
        @*<th>
    @Html.DisplayNameFor(model => model.publicerad)
            @Html.DisplayName("Publicerad")
        </th>*@
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.tavlingsNamn)
            </td>
            <td>
                @*@Html.DisplayFor(modelItem => item.tavlingsDatum)*@
                @item.tavlingsDatum.Value.ToShortDateString()
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.forstaStarttid)
                
            </td>
            <td>
                @*@Html.DisplayFor(modelItem => item.sistaAnmalning)*@
                @item.sistaAnmalning.Value.ToShortDateString()
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.tavlingsForm)
            </td>
            @*<td>
                @Html.DisplayFor(modelItem => item.publicerad)
            </td>*@
            <td>
                @Html.ActionLink("Ändra", "Edit", new { id = item.Id }) |
                @*@Html.ActionLink("Detaljer", "Details", new { id = item.Id }) |*@
                @Html.ActionLink("Ta bort", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>

Golf 3 MVC/Views/tavlings/_aktuelltavling.cshtml
@model Golf_3_MVC.Models.tavling

<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<link href="~/Content/Site.css" rel="stylesheet" />
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<script src="~/Scripts/jquery-3.1.1.js"></script>
<script src="~/Scripts/jquery-3.1.1.min.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>



<table class="table">
    <tr>
        <b>Tävlingsnamn: </b>
        @Model.tavlingsNamn
        <td>
            <b>Form:</b>
            <br />
            @Model.tavlingsForm
        </td>
        <td>
            <b>Datum:</b>
            <br />
            @Model.tavlingsDatum.Value.ToShortDateString()
        </td>
        <td>
            <b>Sista anmälningsdatum:</b>
            <br />
            @Model.sistaAnmalning.Value.ToShortDateString()
        </td>
        <td>
            <b>Starttid:</b>
            <br />
            @Model.forstaStarttid
        </td>
    </tr>

</table>

<br />


@if (User.IsInRole("Personal") || User.IsInRole("Admin"))
{
    <div class="allaanmalda" style="border: 1px solid #414141; border-radius: 5px; margin: 0 auto;  ">

    </div>


    using (Html.BeginForm("LäggTillMedlemPersonal", "tavlings"))
    {
        <script>
            $(document).ready(function () {
                $("#sokmedlem").autocomplete({
                    source: function (request, response) {
                        $.ajax({
                            url: "/Calendar/GetAutoCompleteData",
                            type: "POST",
                            dataType: "json",
                            data: { term: request.term },
                            success: function (data) {
                                response($.map(data, function (item) {
                                    return {
                                        label: item.fornamn, value: item.efternamn, value: item.golf_id
                                    }
                                }))
                            },
                            messages: {
                                noResults: "", results: ""
                            }
                        });
                    }
                });
            });
        </script>

    }


        <p class="pull-right col-lg-6">
            <br />

            <br />
            <input class="center-block success" type="submit" onclick="allaTävlandeIAktuellTävling(this)"
                   data-assigned-id="@Model.Id" value="Se anmälda" />
        </p>
}


@if (User.IsInRole("User"))
{
    <input class="center-block success" type="submit" value="Skicka anmälan" name="skickaAnmalan" onclick="location.href='@Url.Action("LaggTillTavlare", "tavlings")?id=' + @Model.Id" />
    @Html.Raw(TempData["msg"])
}

Golf 3 MVC/Views/tavlings/_allaanmalda.cshtml
@model IEnumerable<Golf_3_MVC.Models.medlemmar>

<table class="table">
    <tr>
        <th>
            @*@Html.DisplayNameFor(model => model.tavlingsNamn)*@
            @Html.DisplayName("Förnamn")
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.tavlingsDatum)*@
            @Html.DisplayName("Efternamn")
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.forstaStarttid)*@
            @Html.DisplayName("Golf-ID")
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.sistaAnmalning)*@
            @Html.DisplayName("Handicap")
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.tavlingsForm)*@
            @Html.DisplayName("Kön")
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.fornamn)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.efternamn)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.golf_id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.hcp)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.kon)
            </td>
        </tr>
    }

</table>